### PR TITLE
Add 'not to have calls satisfying'

### LINKED ISSUE #45: alias 'to have no calls satisfying' as 'not to have calls satisfying'
I just had to look at the docs to figure out why `not to have calls satisfying` was failing :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by joelmukuthu**
Resolves #45

### CODE REVIEW

**Comment by papandreou** [comment]
Let's see if this helps with the CI failures: https://github.com/unexpectedjs/unexpected-sinon/pull/47

**Comment by papandreou** [comment]
There, please rebase on master :)

**Comment by joelmukuthu** [comment]
Thanks @papandreou!

**Comment by sunesimonsen** [comment]
Cool thanks.

**Comment by sunesimonsen** [comment]
@joelmukuthu I have added you as contributor on the package, so you can just merge, release and publish.

**Comment by joelmukuthu** [comment]
Merged and released. While updating the documentation site I noticed that I made an oopsie (https://github.com/unexpectedjs/unexpected-sinon/commit/04334540be756a09875b9b019783d44f33c10fc4) and I just fixed that directly on master and made a patch release, hope that's okay :)

**Comment by sunesimonsen** [comment]
That is okay.

**Pull request merged**
