### PR TITLE
Add a semicolon to the suffix when inspecting a spy call

### PR DESCRIPTION
**Pull request by papandreou**
Makes it more recognizable and copy/pastable when using ... to have calls satisfying <function>

... Unless you don't like semicolons :)

### CODE REVIEW

**Comment by sunesimonsen** [comment]
Sorry but I actually don't think this is an improvement of the output that is already not real JavaScript code. If we could get rid of the surrounding array it might make sense.

**Comment by papandreou** [comment]
Obviously I think it is an improvement on its own (especially because of the copy/pastability), but I don't mind exploring if we can improve the output even further while we're at it :)

First, let's make sure we agree where we're going. I updated the expected output on the branch (0756bf84).

Getting rid of `[` and `]` is easy, but it leaves the indentation (which doesn't seem to be customizable for the `array-like` type) and extraneous newlines when the output is spread over multiple lines. For `spyCalls` it would probably make sense to force the output to be multiline always.

**Comment by papandreou** [comment]
Tried implementing the necessary knobs in Unexpected here: https://github.com/unexpectedjs/unexpected/tree/feature/customizeIndentAndNewlines

Here's what the documentation site looks like with these changes integrated: http://gofish.dk/site-build/

**Comment by sunesimonsen** [comment]
That looks really nice. I'll look at the details tomorrow. 

About the semicolons, the code will not be copy/pastable because of the stack trace, but it is of cause closer.

**Comment by papandreou** [comment]
I'm not totally sure that the type options I introduced for `object` and `array-like` (`multipleLines`, `indent`, `leadingNewline`, `trailingNewline`) are exactly the right ones. Let me know what you think.

**Comment by sunesimonsen** [comment]
I can't help feeling that this is quite messy, but of cause necessary to achieve this functionality. Maybe it would be possible to make a base type for `array-like` that takes care of handling a list of things. Then `array-like` could use the base type to format and diff the items, but would add prefix and suffix and indentation. I don't know if that even makes sense or what such a type should be called. Maybe `list`?
What do you think about such an idea?

**Comment by papandreou** [comment]
Yeah, it's pretty messy all right. Trying to come up with another use case for customizing those diffs like that, but no results yet. Unexpected-dom is pretty well served already. Unexpected-messy could use it if the values of the individual headers used `array-like`, but we can't use the `array-like` assertions because it needs set semantics.

> Maybe it would be possible to make a base type for array-like that takes care of handling a list of things.

Then `list` would be an abstract type with the exact same `inspect` and `diff` as `array-like` has on the `feature/customizeIndentAndNewlines` branch now, right? And we would change the `array-like` assertions to be defined for `list` instead? And `array-like` itself would be quite simple. I suppose that could work?

It would be a breaking change, so I think I would like to also think about how we would model `Set` and how that would fit into things.

**Comment by sunesimonsen** [comment]
My idea was to have an abstract type that can handle a delimited list of things. It would output the items like this:

```js
'item0', 'item1', 'item2', 'item3'
```

or

```js
'item0',
'item1',
'item2',
'item3'
```

`array-like` would then extend this type and just indent it and wrap it with the prefix and suffix. 

I don't see how that is breaking. I'm not talking about moving all the assertion to the base type, but that would not be breaking either.

**Comment by papandreou** [comment]
Ah, now I understand. The inheritance chain would be:

```
           object
             |
             v
      ____ list _ ______
    /        |    \      \
   v         v     v      v
array-like  Set  spyCalls spyCall 
   |
   v
 array```

(If `Set` extends `list`, it should probably be called `collection` instead. It might also turn out to be easier to just extend `object`).

> I'm not talking about moving all the assertion to the base type

The `<array-like> to satisfy <array-like>` assertion would have to be moved to `list`/`collection` to be available to instances of the `spyCalls` type. That's probably also the main challenge -- if the suffixing/prefixing/indentation of the inspect/diff/etc. output happens in the `array-like` type, then there would also have to be an `<array-like> to satisfy <array-like>` assertion that somehow delegated to `<list> to satisfy <list>` (which we can't easily do because we cannot cast) and then also wrap the diff function if the assertion fails.

**Comment by sunesimonsen** [comment]
Yes that was the plan, but I overlooked the casting problem😳

**Comment by papandreou** [comment]
What are you leaning towards, then? Should we block this on casting and move on to that?

**Comment by sunesimonsen** [comment]
I have been thinking about casting, but I can only figure out how to do one level casting.

**Comment by sunesimonsen** [comment]
When I look at the inheritance hierarchy you added, I also have second thoughts entire idea I proposed. The types should be a structuring the actual type hierarchy, not about where to store common output. Maybe it is some utility methods we need, I just don't know where they fit in and I'll really like the API to stop growing.

**Comment by papandreou** [comment]
I'm thinking the naive approach is to maintain an array of active casts (`[{obj: ..., type: ...}, ...]`) in the execution context and take that into account in `expect.findTypeOf`? It'd involve a bit of restructuring, and the execution context would have to be passed to `lookupAssertionRule` etc., but I don't think there'll be much of a performance penalty when there are no active casts.

**Comment by papandreou** [comment]
> The types should be a structuring the actual type hierarchy, not about where to store common output.

Very much agreed, I've been thinking about that as well.

**Comment by sunesimonsen** [comment]
Wouldn't this approach have the following problem:

```
A
^
B
```

```js
foo(A x, A y) { console.log('A A') }
foo(B y, A x) { console.log('B A') }

foo(A x, B y) {
  console.log('A B')
  foo(y, x)
}

var b = new B()
foo((A)b, b)
```

Will print:
```
A B
A A
```
Because we are using the instance to decide if it is casted.

----

But maybe we should look at what strongly typed does. Cast in Java will only affect the dispatch of the method being called in the first level. But the type signature of the method will be propagated to the next level.

```java
class Foo {
  void foo(A x, A y) { println('A A'); }
  void foo(B y, A x) { println('B A'); }

  void foo(A x, B y) {
    println('A B');
    this.foo(y, x);
  }
}

var b = new B();
new Foo().foo((A)b, b);
```
Will print
```
A B
B A
```

If we did something similar we might avoid doing the type lookup again when delegating. But it will of cause still be based on comparing instances which would fail for primitive types and strings.

The idea is that you use the types of the assertion signature when delegating to a nested `expect`. 

A case where this would break down. Having two instances of the same string that has different types in the signature. This actually invalidates this idea, but I just wanted to air it anyways, so you know what I have been thinking about.

**Comment by papandreou** [comment]
With https://github.com/unexpectedjs/unexpected-set we now have:

```
          object
        /       \
       v         v
    array-like   Set
  /     |      \
  v     v       v
array spyCalls spyCall
```

Coincidentally I want to use unexpected-set for matching `HttpConversation` instances in an unordered fashion, and while I'm at it, I thought about making the `HttpConversation` type inherit from `array-like` to take advantage of the advancements that happened in the diffing code. And that actually leads to use case #2 for this, as `HttpConversation`s need to be inspected/diffed without forced indentation.

As `HttpConversation` is currently an object with an `exchanges` property (array), it would probably also require the introduction of `size` and `getItem` methods for `array-like`.

What do you think, would you reconsider https://github.com/unexpectedjs/unexpected/tree/feature/customizeIndentAndNewlines maybe in a slightly cleaned up form? I promise I'll add tests :)

**Comment by sunesimonsen** [comment]
I don't like it, but I don't have great solution to the problem other than duplication which seem even worse. Just do it, while I have my barriers down ;-)

**Comment by sunesimonsen** [comment]
Why is a Set not array-like?

**Comment by papandreou** [comment]
> I don't like it, but I don't have great solution to the problem other than duplication which seem even worse. Just do it, while I have my barriers down ;-)

Thanks-ish :). For the record I'm not that happy with it myself. I'll tweak it a bit, make sure it works for both unexpected-sinon and unexpected-messy, then land it if I can stand the codesmell :)

> Why is a Set not array-like?

I actually haven't even thought about that. Right now it wouldn't work because set elements cannot be retrieved via numerical properties, but if we add support for `size` and `getItem` as I suggested above, it might actually work. It would mean that `to be empty`, `to be non-empty`, `to contain`, `to have items satisfying`, `to have length`, and `when passed as parameters to` would automatically be defined for `Set` instances as well. All of those except `when passed as parameters to` would make sense for `Set`s.

**Comment by papandreou** [comment]
Released in unexpected-sinon 10.0.0.

**Pull request merged**
