### PR TITLE
Switch to evaldown.

### PR DESCRIPTION
**Pull request by alexjeffburke**
This commit wires example update and validation through the tool CLI
and adds the documentation to the build matrix on CI.

### CODE REVIEW

**Comment by sunesimonsen** [comment]
How far is we from being finished here?, it looks pretty ready.

**Comment by alexjeffburke** [comment]
@sunesimonsen actually nothing that I'm aware of, so I've marked it as ready - if you approve of what's here think we can just merge it in :)

**Comment by alexjeffburke** [comment]
@sunesimonsen nudge :) ready to merge if you're happy.

**Review by sunesimonsen — APPROVED** [review]
This is great - thanks 🎉

**Pull request merged**
