### PR TITLE
Implemented 'to have a call satisfying <object|function>'.

### PR DESCRIPTION
**Pull request by papandreou**
Spinoff from #29.

// cc @sunesimonsen @gertsonderby @alexjeffburke @bruderstein

### CODE REVIEW

**Comment by papandreou** [comment]
Some of the error messages can be improved, so consider this a WIP for now. I'm pretty sure the semantics are ok.

**Comment by papandreou** [comment]
The `exhaustively` mode depends on this: https://github.com/unexpectedjs/unexpected/pull/258

**Comment by papandreou** [comment]
Show of hands: Should

```js
expect(spy, 'to have a call satisfying', [ 123 ]);
```

be shorthand for

```js
expect(spy, 'to have a call satisfying', { args: [ 123 ] });
```

?

**Comment by bruderstein** [comment]
:+1: for `expect(spy, 'to have a call satisfying', [ 123 ]);` as a shortcut.

Ideally this same shortcut should work for `'to have calls satisfying'` too.
```js
expect(spy, 'to have calls satisfying', [
   [ 123 ],
   { args: {1: 'foo' } },
   { args: [ 234, 'bar' ] }
 ]);
```

**Comment by sunesimonsen** [comment]
I like shortcuts as long as they are not ambiguous. This one seems fair.

**Comment by alexjeffburke** [comment]
I haven't read the rest of the API to know how well it composed. Agree with @sunesimonsen if it's not ambiguous. I'd be less of a fan if the asserting multiple calls is an array of arrays.. I write something similar on the other recent issue, not sure where that landed though :)

**Comment by alexjeffburke** [comment]
@bruderstein - just read your comment. I'm advocating keeping the multiple and single call assertions distinct enough they *can't* be confused, so I'd rather the args: syntax for one or the other case. (side note thats why in thought a varargs style might be useful to disambiguate).

**Comment by papandreou** [comment]
Implemented shorthands:

* to have a call satisfying [...] => to have a call satisfying { args: [...] }
* to hvae a call satisfying {0: ..., 1: ...} => to have a call satisfying { args: {0: ..., 1: ...} }

The second shorthand kicks in whenever the object has only numerical properties.

**Comment by papandreou** [comment]
@bruderstein @sunesimonsen @alexjeffburke I implemented the shorthands for both `to have a call satisfying` and `to have calls satisfying`. I think they're a nice addition.

**Comment by papandreou** [comment]
@alexjeffburke

> I'd be less of a fan if the asserting multiple calls is an array of arrays

Are you ok with others having that possibility? :)

**Comment by alexjeffburke** [comment]
Haha I'm going to ask you a likely annoying Q but exactly which possibility do you mean? Want to make sure wires aren't crossed :)

What I was getting at, or trying to, is I quite like the multiple calls case using
[
    {args: }, { args: }
]
which I think contrasts well against the short-hands you just implemented.

Wish I could follow these discussions more but I will do what I can to adopt conventions in the few places I 'own'.

**Comment by papandreou** [comment]
@alexjeffburke Hehe, sorry for the confusing comment from me, I think I misread your previous comment :)

I understand that you prefer the explicit version, which is perfectly fine. But it sounds like you think the availability of the shorthand introduces an ambiguity or risk?

**Comment by alexjeffburke** [comment]
Oh no probs! (:

Let me tell you where it came up for context. In -events, I used an array syntax for event matches [bunch, of, things].

Then I implemented multiple events, arrays of arrays and I found myself getting just a little more confused - see the last example in the README. The code seemed to suffer too - check supplied array contains an array. Do different lengths of the arrays inside the array matter? etc etc

But, you know: a) I might be a little too close to the impl side as a basis for my concern b) maybe reading the assertion is enough if you are then very strict about what should go on the RHS.

Lastly, side thought, this interfaces stuff is really tricky!

**Comment by papandreou** [comment]
@alexjeffburke Thanks for elaborating!

> see the last example in the README

Right, I see what you mean. Aren't you missing a `return` in the `it` btw.?

Maybe I'm in a little too deep at this point -- API design is really hard. In this case I think that as long as you have a habit of formatting the `expect` with one expected spy call per line, all of these combinations are perfectly readable:

```js
expect(mySpy, 'to have calls satisfying', [
    [1, 2, 3],
    [4, 5, 6]
]);

expect(mySpy, 'to have calls satisfying', [
    { args: [1, 2, 3] },
    { args: [4, 5, 6] }
]);

expect(mySpy, 'to have calls satisfying', {
    1: [1, 2, 3],
    3: [4, 5, 6]
});

expect(mySpy, 'to have calls satisfying', {
    1: { args: [1, 2, 3] },
    3: { args: [4, 5, 6] }
});
```

As for whether they're *writable* in the sense that you don't find yourself referring to the docs all the time, that's harder to tell. For users that know the `to satisfy` semantics well, I have a feeling they'll try one of the above first. They might not realize that you can also assert the `returnValue`, `thisValue`, `stack`, `threw` etc. which makes it likely that they'll try the array-of-arrays shorthand first -- which would make this change even better.

**Comment by papandreou** [comment]
For completeness, here are the supported variants of `to have a call satisfying` as of the current state of this PR :)

```js
expect(mySpy, 'to have a call satisfying', [ 1, 2, 3 ]);

expect(mySpy, 'to have a call satisfying', { 0: 1, 1: 2 });

expect(mySpy, 'to have a call satisfying', { args: [ 1, 2, 3 ] });

expect(mySpy, 'to have a call satisfying', { args: { 1: 2, 2: 3 } });

expect(mySpy, 'to have a call satisfying', function () {
    mySpy(1, 2, 3);
});
```

**Comment by joelmukuthu** [comment]
:+1: :)

**Comment by sunesimonsen** [comment]
I really like how this turned out. Maybe we should just not touch `was called with` at all and write a deprecation notice in the documentation.

:+1:

**Pull request merged**
