### PR TITLE
Run tests with phantomjs. Closes #24

### LINKED ISSUE #24: Run the test suite using PhantomJS
We need to make sure that the plugin keeps working in a browser based environment, to accommodate this problem, we should run the test suite in PhantomJS like the Unexpected test suite.

### PR DESCRIPTION
**Pull request by Munter**

### CODE REVIEW

**Comment by sunesimonsen** [comment]
@Munter thanks - it seems like we don't get stack traces from phantom, so the tests are failing.

**Comment by Munter** [comment]
Yeah, @papandreou noticed that yesterday. Now it's tracked though :)

**Comment by papandreou** [comment]
https://github.com/sinonjs/sinon/pull/1023

**Comment by papandreou** [comment]
Made it work with the Sinon fix here: https://github.com/unexpectedjs/unexpected-sinon/tree/phantom

**Comment by papandreou** [comment]
Landed as part of #34, thanks :)

**Pull request closed without merging**
